routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');
Route::get('dataTableUSer', 'UserController@dataTable')->name('dataTableUser');

Route::resource('roles', 'RolesController');
Route::get('dataTableRoles', 'RolesController@dataTable')->name('dataTableRoles');

app/User.php
<?php

namespace App;

use App\Traits\HasRolesAndPermissions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable,HasRolesAndPermissions;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = User::all();
        $names = $user->sortBy('name')->pluck('name')->unique();
        $emails = $user->sortBy('email')->pluck('email')->unique();
        return view('user.index', compact('names', 'emails'));
    }

    public function dataTable()
    {
        return DataTables::of(User::select('id', 'name', 'email', 'created_at')->where('id', '<>', 1)->get())
            ->editColumn('created_at', function(User $user){
                return $user->created_at->diffForHumans();
            })
            ->addColumn('btn', 'user.dataTable.btn')
            ->rawColumns(['btn'])
            ->toJson();
    }

    public function create(Request $request)
    {
        if($request->ajax()){
            $roles = Role::where('id', $request->role_id)->first();
            $permissions = $roles->permissions;

            return $permissions;
        }
        $roles = Role::all();
        return view('user.create')->with('roles',$roles);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|unique:users|email|max:255',
            'password' => 'required|between:8,255|confirmed',
            'password_confirmation' => 'required',
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);

        try {
            $user->save();

            if($request->role != null){
                $user->roles()->attach($request->role);
                $user->save();
            }

            if($request->permissions != null){
                foreach ($request->permissions as $permission) {
                    $user->permissions()->attach($permission);
                    $user->save();
                }
            }

            return back()->with('success','Registro Guardado');
        } catch (Exception $e) {
            return back()->with('error',$e);
        }

    }

    public function show(User $user)
    {
        if($user->id==1 && Auth::id()<>1){
            abort(403);
        }
        return view('user.show')->with('user',$user);
    }

    public function edit(User $user)
    {
        if($user->id==1 && Auth::id()<>1){
            abort(403);
        }

        $roles = Role::get();
        $userRole = $user->roles->first();

        if($user->id==1 && Auth::id()<>1){
            abort(403);
        }

        if($userRole != null){
            $rolePermissions = $userRole->allRolePermissions;
        }else{
            $rolePermissions = null;
        }
        $userPermissions = $user->permissions;

        return view('user.edit', [
            'user'=>$user,
            'roles'=>$roles,
            'userRole'=>$userRole,
            'rolePermissions'=>$rolePermissions,
            'userPermissions'=>$userPermissions
        ]);

    }

    public function update(Request $request, User $user)
    {
        if($user->id==1 && Auth::id()<>1){
            abort(403);
        }
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
            'password' => 'confirmed',
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password != null){
            $user->password = Hash::make($request->password);
        }
        $user->save();

        $user->roles()->detach();
        $user->permissions()->detach();

        if($request->role != null){
            $user->roles()->attach($request->role);
            $user->save();
        }

        if($request->permissions != null){
            foreach ($request->permissions as $permission) {
                $user->permissions()->attach($permission);
                $user->save();
            }
        }

        return back()->with('success','Registro Guardado');
    }

    public function destroy(User $user)
    {
        if($user->id==1 && Auth::id()<>1){
            abort(403);
        }
        $user->roles()->detach();
        $user->permissions()->detach();
        $user->delete();
        return redirect()->back()->with('success','Registro Borrardo');
    }
}

resources/views/user/create.blade.php
@extends('layouts.argon')

@section('content')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Nuevo</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('user.store') }}" method="POST">
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="name">Nombre</label>
                                        <input type="text" id="" class="form-control" name="name" placeholder="Enter your name" value="">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-control-label" for="email">Correo</label>
                                        <input type="email" id="" name="email" class="form-control" placeholder="example@example.com">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-control-label" for="password">Contraseña</label>
                                        <input type="password" id="" name="password" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-control-label" for="password">Confirmar</label>
                                        <input type="password" id="" name="password_confirmation" class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="role">Rol</label>
                                        <select name="role" class="form-control" id="role" required>
                                            <option value="">Seleccione un rol:</option>
                                            @foreach($roles as $role)
                                                <option data-role-id="{{$role->id}}"
                                                        data-role-slug="{{$role->slug}}"
                                                        value="{{$role->id}}">{{$role->nombre}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group" id="permissions_box">
                                        <label class="form-control-label" for="permisos">Permisos</label>
                                        <div id="permissions_ckeckbox_list"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-sm btn-success"><i class="fas fa-save"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            var permissions_box = $('#permissions_box');
            var permissions_ckeckbox_list = $('#permissions_ckeckbox_list');
            permissions_box.hide();

            $('#role').on('change', function() {
                var role = $(this).find(':selected');
                var role_id = role.data('role-id');
                var role_slug = role.data('role-slug');
                permissions_ckeckbox_list.empty();
                $.ajax({
                    url: "/user/create",
                    method: 'get',
                    dataType: 'json',
                    data: {
                        role_id: role_id,
                        role_slug: role_slug,
                    }
                }).done(function(data) {
                    permissions_box.show();
                    $.each(data, function(index, element){
                        $(permissions_ckeckbox_list).append(
                            '<div class="custom-control custom-checkbox">'+
                            '<input class="custom-control-input" type="checkbox" name="permissions[]" id="'+ element.slug +'" value="'+ element.id +'">' +
                            '<label class="custom-control-label" for="'+ element.slug +'">'+ element.nombre +'</label>'+
                            '</div>'
                        );
                    });
                });
            });
        });
    </script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.argon')

@section('content')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Editar</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('user.update', $user->id) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="name">Name</label>
                                        <input type="text" id="" class="form-control" name="name" value="{{ $user->name }}">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-control-label" for="email">Email address</label>
                                        <input type="email" id="" name="email" class="form-control" value="{{ $user->email }}">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-control-label" for="password">Password</label>
                                        <input type="password" id="" name="password" class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="role">Rol</label>
                                        <select name="role" class="form-control" id="role" required>
                                            <option value="">Seleccione un rol:</option>
                                            @foreach($roles as $role)
                                                <option data-role-id="{{$role->id}}" data-role-slug="{{$role->slug}}" value="{{$role->id}}" {{ $user->roles->isEmpty() || $role->nombre != $userRole->nombre ? "" : "selected"}}>{{$role->nombre}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group" id="permissions_box">
                                        <label class="form-control-label" for="permisos">Permisos</label>
                                        <div id="permissions_ckeckbox_list"></div>
                                    </div>
                                    @if($user->permissions->isNotEmpty())
                                        @if($rolePermissions != null)
                                            <div id="user_permissions_box" >
                                                <label for="roles">User Permissions</label>
                                                <div id="user_permissions_ckeckbox_list">
                                                    @foreach ($rolePermissions as $permission)
                                                        <div class="custom-control custom-checkbox">
                                                            <input class="custom-control-input" type="checkbox" name="permissions[]" id="{{$permission->slug}}" value="{{$permission->id}}" {{ in_array($permission->id, $userPermissions->pluck('id')->toArray() ) ? 'checked="checked"' : '' }}>
                                                            <label class="custom-control-label" for="{{$permission->slug}}">{{$permission->nombre}}</label>
                                                        </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        @endif
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-sm btn-success"><i class="fas fa-save"></i> Actualizar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            var permissions_box = $('#permissions_box');
            var permissions_ckeckbox_list = $('#permissions_ckeckbox_list');
            var user_permissions_box = $('#user_permissions_box');
            var user_permissions_ckeckbox_list = $('#user_permissions_ckeckbox_list');
            permissions_box.hide(); // hide all boxes
            $('#role').on('change', function() {
                var role = $(this).find(':selected');
                var role_id = role.data('role-id');
                var role_slug = role.data('role-slug');
                permissions_ckeckbox_list.empty();
                user_permissions_box.empty();
                $.ajax({
                    url: "/user/create",
                    method: 'get',
                    dataType: 'json',
                    data: {
                        role_id: role_id,
                        role_slug: role_slug,
                    }
                }).done(function(data) {
                    permissions_box.show();
                    $.each(data, function(index, element){
                        $(permissions_ckeckbox_list).append(
                            '<div class="custom-control custom-checkbox">'+
                            '<input class="custom-control-input" type="checkbox" name="permissions[]" id="'+ element.slug +'" value="'+ element.id +'">' +
                            '<label class="custom-control-label" for="'+ element.slug +'">'+ element.nombre +'</label>'+
                            '</div>'
                        );
                    });
                });
            });
        });
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.argon')

@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Usuarios</h3>
          </div>
          <div class="col text-right">
            <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Nuevo</a>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush" id="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nombre</th>
              <th scope="col">Correo</th>
              <th scope="col">Creado</th>
              <th scope="col">Opciones</th>
            </tr>
          </thead>
          <tbody></tbody>
          <tfoot>
            <tr>
              <td></td>
              <td>
                <input type="text" class="form-control filter-input" placeholder="Buscar por nombre" data-column="1" />
              </td>
              <td>
                <input type="text" class="form-control filter-input" placeholder="Buscar por correo" data-column="2" />
              </td>
              <td></td>
              <td></td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  $(document).ready(function(){
    var table = $('#table').DataTable({
      processing: true,
      serverSider: true,
      ajax: '{!! route('dataTableUser') !!}',
      columns: [
        {data: 'id'},
        {data: 'name'},
        {data: 'email'},
        {data: 'created_at'},
        {data: 'btn' },
      ],
      "columnDefs":[
      //  {
      //    "render": function(data, type, row){
      //      return data +' - '+row['email'];
      //    },
      //    "targets": 1
      //  },
        {
          "visible": false, "targets": [0]
        }
      ],
      "dom": 'lrtip',
      "language":{
          "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json",
          "info": "_TOTAL_ Registros",
          "search": "Buscar",
          "paginate":{
              "next": "Siguiente",
              "previous": "Anterior"
          },
          "loadingRecords": "Cargando...",
          "processing": "Procesando",
          "emptyTable": "No hay registros",
          "zeroRecords": "Sin registros"
      }
    });
    $('.filter-input').keyup(function(){
      table.column($(this).data('column'))
      .search($(this).val())
      .draw();
    });
  });
  </script>
@endsection

resources/views/user/show.blade.php
@extends('layouts.argon')

@section('content')
<div class="card">
  <div class="card-header">
    <div class="row align-items-center">
        <div class="col-8">
            <h3 class="mb-0">Detalle</h3>
        </div>
        <div class="col-4 text-right">
            <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
        </div>
    </div>
  </div>
  <div class="card-body">
    <div class="mb-2">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <th> Nombre </th>
            <td> {{ $user->name }} </td>
          </tr>
          <tr>
            <th> Correo </th>
            <td> {{ $user->email }} </td>
          </tr>
          <tr>
            <th> Roles </th>
            <td>
                @if ($user->roles->isNotEmpty())
                    @foreach($user->roles as $role)
                        <span class="badge badge-info">{{$role->nombre}}</span>
                    @endforeach
                @else
                    <span class="badge badge-info">Sin Rol asignado</span>
                @endif
            </td>
          </tr>
          <tr>
              <th> Permisos </th>
              <td>
                  @if ($user->permissions->isNotEmpty())
                      @foreach($user->permissions as $permissions)
                          <span class="badge badge-info">{{$permissions->nombre}}</span>
                      @endforeach
                  @else
                      <span class="badge badge-info">Sin permisos asignados</span>
                  @endif
              </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection