routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');
Route::get('dataTableUSer', 'UserController@dataTable')->name('dataTableUser');

Route::resource('roles', 'RolesController');
Route::get('dataTableRoles', 'RolesController@dataTable')->name('dataTableRoles');

resources/views/include/content.blade.php
@yield('content')

resources/views/include/footer.blade.php
<div class="row align-items-center justify-content-lg-between">
  <div class="col-lg-6">
    <div class="copyright text-center  text-lg-left  text-muted">
      &copy; {{date('Y')}} {{env('APP_NAME')}}
    </div>
  </div>
  <div class="col-lg-6">
    <ul class="nav nav-footer justify-content-center justify-content-lg-end">
      <li class="nav-item">
        <a href="" class="nav-link" target="_blank"></a>
      </li>
    </ul>
  </div>
</div>

resources/views/include/header.blade.php
<div class="container-fluid">
    <div class="header-body">
        <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
                <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="/{{request()->segment(1)}}">{{ ucwords(request()->segment(1)) }}</a></li>
                        @if (request()->segment(2))
                            <li class="breadcrumb-item"><a href="#">{{ ucwords(request()->segment(2)) }}</a></li>
                            <li class="breadcrumb-item"><a href="#">{{ ucwords(request()->segment(3)) }}</a></li>
                        @endif
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

resources/views/include/menu.blade.php
<div class="collapse navbar-collapse" id="sidenav-collapse-main">
    <ul class="navbar-nav">

        <li class="nav-item">
            <a class="nav-link {{(request()->segment(1)=='home') ? 'active':'' }}" href="{{ route('home') }}">
                <i class="ni ni-tv-2 text-orange"></i>
                <span class="nav-link-text">Inicio</span>
            </a>
        </li>

        @canany(['isAdmin','isUser'])
        <li class="nav-item">
            <a class="nav-link {{(request()->segment(1)=='user') ? 'active':'' }}" href="{{ route('user.index') }}">
                <i class="ni ni-single-02 text-orange"></i>
                <span class="nav-link-text">Usuarios</span>
            </a>
        </li>
        @endcanany

        @canany(['isAdmin'])
        <li class="nav-item">
            <a class="nav-link {{(request()->segment(1)=='roles') ? 'active':'' }}" href="{{ route('roles.index') }}">
                <i class="ni ni-paper-diploma text-orange"></i>
                <span class="nav-link-text">Roles</span>
            </a>
        </li>
        @endcanany

    </ul>
</div>

resources/views/include/navbar.blade.php
<ul class="navbar-nav align-items-center  ml-md-auto ">
  <li class="nav-item d-xl-none">
    <!-- Sidenav toggler -->
    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
      <div class="sidenav-toggler-inner">
        <i class="sidenav-toggler-line"></i>
        <i class="sidenav-toggler-line"></i>
        <i class="sidenav-toggler-line"></i>
      </div>
    </div>
  </li>
  <li class="nav-item d-sm-none">
    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
      <i class="ni ni-zoom-split-in"></i>
    </a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="ni ni-bell-55"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
      <!-- Dropdown header -->
      <div class="px-3 py-3">
        <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.
        </h6>
      </div>
      <!-- List group -->
      <div class="list-group list-group-flush">
        <a href="#!" class="list-group-item list-group-item-action">
          <div class="row align-items-center">
            <div class="col-auto">
              <!-- Avatar -->
              <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-1.jpg') }}" class="avatar rounded-circle">
            </div>
            <div class="col ml--2">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="mb-0 text-sm">John Snow</h4>
                </div>
                <div class="text-right text-muted">
                  <small>2 hrs ago</small>
                </div>
              </div>
              <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
            </div>
          </div>
        </a>
        <a href="#!" class="list-group-item list-group-item-action">
          <div class="row align-items-center">
            <div class="col-auto">
              <!-- Avatar -->
              <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-2.jpg') }}" class="avatar rounded-circle">
            </div>
            <div class="col ml--2">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="mb-0 text-sm">John Snow</h4>
                </div>
                <div class="text-right text-muted">
                  <small>3 hrs ago</small>
                </div>
              </div>
              <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
            </div>
          </div>
        </a>
        <a href="#!" class="list-group-item list-group-item-action">
          <div class="row align-items-center">
            <div class="col-auto">
              <!-- Avatar -->
              <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-3.jpg') }}" class="avatar rounded-circle">
            </div>
            <div class="col ml--2">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="mb-0 text-sm">John Snow</h4>
                </div>
                <div class="text-right text-muted">
                  <small>5 hrs ago</small>
                </div>
              </div>
              <p class="text-sm mb-0">Your posts have been liked a lot.</p>
            </div>
          </div>
        </a>
        <a href="#!" class="list-group-item list-group-item-action">
          <div class="row align-items-center">
            <div class="col-auto">
              <!-- Avatar -->
              <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-4.jpg') }}" class="avatar rounded-circle">
            </div>
            <div class="col ml--2">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="mb-0 text-sm">John Snow</h4>
                </div>
                <div class="text-right text-muted">
                  <small>2 hrs ago</small>
                </div>
              </div>
              <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
            </div>
          </div>
        </a>
        <a href="#!" class="list-group-item list-group-item-action">
          <div class="row align-items-center">
            <div class="col-auto">
              <!-- Avatar -->
              <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-5.jpg') }}" class="avatar rounded-circle">
            </div>
            <div class="col ml--2">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="mb-0 text-sm">John Snow</h4>
                </div>
                <div class="text-right text-muted">
                  <small>3 hrs ago</small>
                </div>
              </div>
              <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
            </div>
          </div>
        </a>
      </div>
      <!-- View all -->
      <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
    </div>
  </li>
</ul>
<ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
  <li class="nav-item dropdown">
    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <div class="media align-items-center">
        <span class="avatar avatar-sm rounded-circle">
          <img alt="Image placeholder" src="{{ asset('assets/img/theme/team-4.jpg') }}">
        </span>
        <div class="media-body  ml-2  d-none d-lg-block">
          <span class="mb-0 text-sm  font-weight-bold">
              @auth
                  {{ Auth::user()->name }} ({{ Auth::user()->roles->isNotEmpty() ? Auth::user()->roles->first()->nombre : "" }})
              @endauth
          </span>
        </div>
      </div>
    </a>
    <div class="dropdown-menu  dropdown-menu-right ">
      <div class="dropdown-header noti-title">
        <h6 class="text-overflow m-0">Bienvenido!</h6>
      </div>
      <a href="#!" class="dropdown-item">
        <i class="ni ni-single-02"></i>
        <span>Mi Perfil</span>
      </a>
      <a href="#!" class="dropdown-item">
        <i class="ni ni-settings-gear-65"></i>
        <span>Configuraciones</span>
      </a>
      <a href="#!" class="dropdown-item">
        <i class="ni ni-support-16"></i>
        <span>Soporte</span>
      </a>
      <div class="dropdown-divider"></div>
      <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
        <i class="ni ni-user-run"></i>
        <span>Salir</span>
      </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
    </div>
  </li>
</ul>

resources/views/include/search.blade.php
<form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
  <div class="form-group mb-0">
    <div class="input-group input-group-alternative input-group-merge">
      <div class="input-group-prepend">
        <span class="input-group-text"><i class="fas fa-search"></i></span>
      </div>
      <input class="form-control" placeholder="Buscar..." type="text">
    </div>
  </div>
  <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</form>