routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');
Route::get('dataTableUSer', 'UserController@dataTable')->name('dataTableUser');

Route::resource('roles', 'RolesController');
Route::get('dataTableRoles', 'RolesController@dataTable')->name('dataTableRoles');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['nombre','slug'];

    public function permissions()
    {
        return $this->belongsToMany(\App\Models\Permission::class,'roles_permissions');
    }

    public function allRolePermissions()
    {
        return $this->belongsToMany(\App\Models\Permission::class, 'roles_permissions');
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Gate;

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Role $role)
    {
        $this->authorize('viewAny',$role);
        return view('roles.index');
    }

    public function dataTable(Role $role)
    {
        $this->authorize('viewAny',$role);
        $role = Role::select('id', 'nombre', 'slug')->get();
        return DataTables::of($role)
            ->addColumn('btn', 'roles.dataTable.btn')
            ->rawColumns(['btn'])
            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Role $role)
    {
        $this->authorize('create',$role);
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Role $role)
    {
        $this->authorize('create',$role);
        $request->validate([
            'nombre' => 'required|max:255|unique:roles',
            'slug' => 'required|unique:roles|max:255',
        ]);

        $role = new Role();

        $role->nombre = $request->nombre;
        $role->slug = $request->slug;
        $role->save();

        $list = explode(',',$request->roles_permissions);

        foreach ($list as $permiso){
            $permissions = new Permission();
            $permissions->nombre = $permiso;
            $permissions->slug = strtolower(str_replace(" ","-",$permiso));
            $permissions->save();
            $role->permissions()->attach($permissions->id);
            $role->save();
        }

        try {
            return back()->with('success','Registro Guardado');
        } catch (Exception $e) {
            return back()->with('error',$e);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $this->authorize('view',$role);
        return view('roles.show')->with('role',$role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->authorize('update',$role);
        return view('roles.edit')->with('roles',$role);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {

        $this->authorize('update',$role);

        $request->validate([
            'nombre' => 'required|max:255',
            'slug' => 'required|max:255',
        ]);

        $role->nombre = $request->nombre;
        $role->slug = $request->slug;

        try {
            $role->save();

            $role->permissions()->delete();
            $role->permissions()->detach();

            $list = explode(',',$request->roles_permissions);

            foreach ($list as $permiso){
                $permissions = new Permission();
                $permissions->nombre = $permiso;
                $permissions->slug = strtolower(str_replace(" ","-",$permiso));
                $permissions->save();
                $role->permissions()->attach($permissions->id);
                $role->save();
            }

            return back()->with('success','Registro Guardado');
        } catch (Exception $e) {
            return back()->with('error',$e);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete',$role);
        $role->permissions()->delete();
        $role->delete();
        $role->permissions()->detach();
        return redirect()->back()->with('success','Registro Borrardo');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.argon')

@section('content')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Nuevo</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('roles.store') }}" method="POST">
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="name">Nombre</label>
                                        <input type="text" id="nombre" class="form-control" name="nombre" placeholder="Nombre" value="">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="email">Slug</label>
                                        <input type="text" id="slug" name="slug" class="form-control" placeholder="Slug" readonly>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="form-control-label" for="email">Permisos</label>
                                        <input type="text" data-role="tagsinput" name="roles_permissions" class="form-control" placeholder="Permisos">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-sm btn-success"><i class="fas fa-save"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $('#nombre').keyup(function(e){
                var str = $('#nombre').val();
                str = str.replace(/\W+(?!$)/g, '-').toLowerCase();
                $('#slug').val(str);
                $('#slug').attr('placeholder', str);
            });
        });
    </script>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.argon')

@section('content')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Editar</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('roles.update', $roles->id) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="nombre">Nombre</label>
                                        <input type="text" id="nombre" class="form-control" name="nombre" value="{{ $roles->nombre }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="slug">Slug</label>
                                        <input type="text" id="slug" name="slug" class="form-control" value="{{ $roles->slug }}" readonly>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="form-control-label" for="email">Permisos</label>
                                        <input type="text"
                                               data-role="tagsinput"
                                               name="roles_permissions"
                                               value="@foreach ($roles->permissions as $permission){{ $permission->nombre.',' }}@endforeach"
                                               class="form-control"
                                               placeholder="Permisos">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-sm btn-success"><i class="fas fa-save"></i> Actualizar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
    $(document).ready(function(){
        $('#nombre').keyup(function(e){
            var str = $('#nombre').val();
            str = str.replace(/\W+(?!$)/g, '-').toLowerCase();
            $('#slug').val(str);
            $('#slug').attr('placeholder', str);
        });
    });
</script>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.argon')

@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Roles</h3>
          </div>
          <div class="col text-right">
            <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Nuevo</a>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush" id="table">
          <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Role</th>
                <th scope="col">Slug</th>
                <th scope="col">Opciones</th>
            </tr>
          </thead>
          <tbody></tbody>
            <tfoot>
            <tr>
                <td></td>
                <td>
                    <input type="text" class="form-control filter-input" placeholder="Buscar por nombre" data-column="1" />
                </td>
                <td>
                    <input type="text" class="form-control filter-input" placeholder="Buscar por correo" data-column="2" />
                </td>
                <td></td>
            </tr>
            </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  $(document).ready(function(){
    var table = $('#table').DataTable({
      processing: true,
      serverSider: true,
      ajax: '{!! route('dataTableRoles') !!}',
      columns: [
          {data: 'id'},
          {data: 'nombre'},
          {data: 'slug'},
          {data: 'btn'},
      ],
        "columnDefs":[
            //  {
            //    "render": function(data, type, row){
            //      return data +' - '+row['email'];
            //    },
            //    "targets": 1
            //  },
            {
                "visible": false, "targets": [0]
            }
        ],
        "dom": 'lrtip',
        "language":{
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json",
            "info": "_TOTAL_ Registros",
            "search": "Buscar",
            "paginate":{
                "next": "Siguiente",
                "previous": "Anterior"
            },
            "loadingRecords": "Cargando...",
            "processing": "Procesando",
            "emptyTable": "No hay registros",
            "zeroRecords": "Sin registros"
        }
    });
      $('.filter-input').keyup(function(){
          table.column($(this).data('column'))
              .search($(this).val())
              .draw();
      });
  });
</script>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.argon')

@section('content')
<div class="card">
  <div class="card-header">
    <div class="row align-items-center">
        <div class="col-8">
            <h3 class="mb-0">Detalle</h3>
        </div>
        <div class="col-4 text-right">
            <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary"><i class="fas fa-arrow-circle-left"></i> Volver</a>
        </div>
    </div>
  </div>
  <div class="card-body">
    <div class="mb-2">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <th> Nombre </th>
            <td> {{ $role->nombre }} </td>
          </tr>
          <tr>
            <th> Slug </th>
            <td> {{ $role->slug }} </td>
          </tr>
          <tr>
            <th> Permisos </th>
            <td>
                @if ($role->permissions != null)
                    @foreach($role->permissions as $permission)
                        <span class="badge badge-info">{{$permission->nombre}}</span>
                    @endforeach
                @endif
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection